config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'users/mypage' => 'users#show'
    patch 'users/mypage' => 'users#update'
    get 'users/mypage/edit' => 'users#edit'
    get 'users/unsubscribe'
    patch 'users/withdrawal'
    resources :areas, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :area_comments, only: [:create, :destroy]
    end
    get 'favorites/index'
    get 'area_comments/index'
    get "search" => "areas#search"
    get "jmapsearch" => "areas#jmapsearch"
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :areas, only: [:index, :show, :edit, :update, :destroy] do
      resources :area_comments, only: [:update, :destroy]
    end
  end

  scope module: :admin do
    resources :area_comments, only: [:index, :show, :edit]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area_comment.rb
class AreaComment < ApplicationRecord

  belongs_to :user
  belongs_to :area

  validates :comment, presence: true

end

app/controllers/admin/area_comments_controller.rb
class Admin::AreaCommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @area_comments = AreaComment.all.page(params[:page]).per(5)
  end

  def show
    @area_comment = AreaComment.find(params[:id])
  end

  def edit
    @area_comment = AreaComment.find(params[:id])
  end

  def update
    @area_comment = AreaComment.find(params[:id])
    if @area_comment.update(area_comment_params)
      flash[:notice] = "変更保存しました"
      redirect_to area_comment_path(@area_comment)
    else
      render :edit
    end
  end

  def destroy
    AreaComment.find(params[:id]).destroy
    flash[:notice] = "削除しました"
    redirect_to area_comments_path
  end

  private

  def area_comment_params
    params.require(:area_comment).permit(:comment)
  end
end

app/helpers/admin/area_comments_helper.rb
module Admin::AreaCommentsHelper
end

app/views/admin/area_comments/edit.html.erb
<div class="container">
   <div class="row mt-4">
    <div class="col-10 mx-auto">
      <h2 class="text-center w-25 h4 bg-light">コメント編集</h2>
      <%= render 'layouts/errors', obj: @area_comment %>
    </div>
  </div>

  <div class="row">
    <div class="col-10 mx-auto">
      <%= form_with model: @area_comment, url: admin_area_area_comment_path(@area_comment), method: :patch do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td class="col-4">コメント</td>
              <td><%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "form-control col-6" %></td>
            </tr>
            <tr>
              <td><%= f.submit "保存する", class: 'btn btn-success' %></td>
              <td><%= link_to "削除する", admin_area_area_comment_path(@area_comment), method: :delete, class: 'btn btn-danger' %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/area_comments/index.html.erb
<div class="container">
   <div class="row mt-4">
    <div class="col-10 mx-auto">
      <h2 class="text-center w-25 h4 bg-light">コメント一覧</h2>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-10 mx-auto">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>施設名</th>
            <th>住所</th>
            <th>コメント</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @area_comments.each do |area_comment| %>
          <tr>
            <td><%= area_comment.area.area_name %></td>
            <td><%= area_comment.area.address %></td>
            <td><%= area_comment.comment %></td>
            <td><%= link_to "詳細", area_comment_path(area_comment), class: 'btn btn-success' %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @area_comments %>
      </div>
    </div>
  </div>
</div>

app/views/admin/area_comments/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-10 mx-auto">
      <h2 class="text-center w-25 h4 bg-light">コメント詳細</h2>
    </div>
  </div>
  
  <div class="row mt-4">
    <div class="col-10 mx-auto">
      <table class="table table-bordered mt-3">
        <tbody>
          <tr>
            <td class="table-active text-dark w-50">ユーザー名</td>
            <td class="w-100"><%= @area_comment.user.name %></td>
          </tr>
          <tr>
            <td class="table-active text-dark">メールアドレス</td>
            <td class="w-100"><%= @area_comment.user.email %></td>
          </tr>
          <tr>
            <td class="table-active text-dark">コメント</td>
            <td class="w-100"><%= @area_comment.comment %></td>
          </tr>
        </tbody>
      </table>
      <div class="mt-3">
        <%= link_to "コメント編集", edit_area_comment_path, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>