config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'users/mypage' => 'users#show'
    patch 'users/mypage' => 'users#update'
    get 'users/mypage/edit' => 'users#edit'
    get 'users/unsubscribe'
    patch 'users/withdrawal'
    resources :areas, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :area_comments, only: [:create, :destroy]
    end
    get 'favorites/index'
    get 'area_comments/index'
    get "search" => "areas#search"
    get "jmapsearch" => "areas#jmapsearch"
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :areas, only: [:index, :show, :edit, :update, :destroy] do
      resources :area_comments, only: [:update, :destroy]
    end
  end

  scope module: :admin do
    resources :area_comments, only: [:index, :show, :edit]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :areas, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :area_comments, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "変更保存しました"
      redirect_to admin_user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <h2 class="card-header bg-light"><%= @user.name %>さんの会員情報編集</h2>
          <%= render 'layouts/errors', obj: @user %>
          <%= form_with model: @user,url: admin_user_path(@user),method: :patch do |f| %>
          <div class="card-body">
            <table class="table table-borderless">
              <tbody>
                <tr>
                  <td>会員ID</td>
                  <td><%= @user.id %></td>
                </tr>
                <tr>
                  <td>ユーザー名</td>
                  <td><%= f.text_field :name, class: "form-control" %></td>
                </tr>
                <tr>
                  <td>メールアドレス</td>
                  <td><%= f.text_field :email, class: "form-control", placeholder: "example@example.com" %></td>
                </tr>
                <tr>
                  <td>会員ステータス</td>
                  <td class="form-check form-check-inline">
                    <%= f.radio_button :is_deleted, false, class: "form-check-input", id: "is_active" %>
                    <%= f.label :is_deleted, "有効", { value: :false, for: "is_active", class: "form-check-label" } %>
                  </td>
                  <td class="form-check form-check-inline">
                    <%= f.radio_button :is_deleted, true, class: "form-check-input", id: "is_deleted" %>
                    <%= f.label :is_deleted, "退会", { value: :true, for: "is_deleted", class: "form-check-label" } %>
                  </td>
                  </tr>
                  <tr>
                    <td></td>
                    <td><%= f.submit "変更を保存", class: "btn btn-success btn-lg" %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
    <div class="row mt-4">
      <div class="col-10 mx-auto">
        <h2 class="text-center bg-light h4 col-3">会員一覧</h2>
      </div>
    </div>

  <div class="row mt-4">
    <div class="col-11 mx-auto">
      <table class="table">
        <thead>
          <tr class="text-center">
            <th>会員ID</th>
            <th>ユーザー名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="text-center">
              <td><%= user.id %></td>
              <td><%= link_to user.name,admin_user_path(user) %></td>
              <td><%= user.email %></td>
                <% if user.is_deleted %>
                  <td>退会済み</td>
                <% else %>
                  <td class="text-success">有効</td>
                <% end %>
            </tr>
          <% end %>
        </tbody>
       </table>
        <div class="d-flex justify-content-center">
          <%= paginate @users %>
        </div>
      </div>
   </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <h2 class="card-header bg-light"><%= @user.name %>さんの会員詳細</h2>
        <div class="card-body">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td>会員ID</td>
                <td><%= @user.id %></td>
              </tr>
              <tr>
                <td>ユーザー名</td>
                <td><%= @user.name %></td>
              </tr>
              <tr>
                <td>メールアドレス</td>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <td>会員ステータス</td>
                <td>
                  <% if @user.is_deleted %>
                    退会
                  <% else %>
                    <div class="text-success">有効</div>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
          <%= link_to "編集する", edit_admin_user_path, class: "btn btn-success mr-3" %>
        </div>
      </div>
    </div>
  </div>
</div>