config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'users/mypage' => 'users#show'
    patch 'users/mypage' => 'users#update'
    get 'users/mypage/edit' => 'users#edit'
    get 'users/unsubscribe'
    patch 'users/withdrawal'
    resources :areas, only: [:new, :create, :show, :edit, :update, :destroy, :index] do
      resource :favorites, only: [:index, :create, :destroy]
      resources :area_comments, only: [:create, :destroy]
    end
    get 'favorites/index'
    get 'area_comments/index'
    get "search" => "areas#search"
    get "jmapsearch" => "areas#jmapsearch"
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :areas, only: [:index, :show, :edit, :update, :destroy] do
      resources :area_comments, only: [:update, :destroy]
    end
  end

  scope module: :admin do
    resources :area_comments, only: [:index, :show, :edit]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラーが発生しました
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_footer.html.erb
<div class="py-2 mt-5" style="background-color: #FFF5EE;">
  <div class="container">
    <div class="text-center">
      <p class="mb-0" style="font-size: 14px;">&copy; 2023 どこでもトイレ All Rights Reserved</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="py-2" style="background-color: #FFF5EE;">
    <div class="container">
      <div class="d-flex justify-content-between">
        <h1>
          <%= link_to root_path, data: {"turbolinks"=>false} do %>
            <%= image_tag 'linkedin_banner_image_1.png', class: "rounded-circle mb-0", style: "height: 96px; line-height: 96px;" %>
          <% end %>
        </h1>
          <div class="f-flex flex-column">
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFF5EE;">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <% if user_signed_in? %>
                 <li class="nav-item">
                    <%= link_to 'マイページ', users_mypage_path, class: "nav-link text-dark border rounded btn mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '新規投稿', new_area_path, class: "nav-link text-dark border rounded btn mr-3" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-dark border rounded btn' %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to '会員一覧', admin_users_path, class: "nav-link text-dark border rounded mr-3 btn" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '投稿一覧', admin_areas_path, class: "nav-link text-dark border rounded mr-3 btn" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'コメント一覧', area_comments_path, class: "nav-link text-dark border rounded mr-3 btn" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link text-dark border rounded btn" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to '新規登録', new_user_registration_path, class: 'nav-link text-dark border rounded btn mr-3' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-dark border rounded btn' %>
                  </li>
                <% end %>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TamokutekiToilet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="container">
        <div class="mt-3 alert alert" role="alert">
          <%= flash[:notice] %>
        </div>
      </div>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>